[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.8.9", features = ["macros"] }
http = "1.4.2"
serde = { version = "1.0.228", features = ["derive"] }
tracing-subscriber = "0.3.23"
ticket_fields = { path = "../../../helpers/ticket_fields" }
